FROM splitbrain/phpfarm:jessie

RUN apt-get update
RUN apt-get install -y --no-install-recommends unzip wget autoconf build-essential

ENV REDIS_HOST redis

RUN wget https://github.com/phpredis/phpredis/archive/master.zip -O /tmp/phpredis-master.zip

RUN mkdir /tmp/phpredis-5.6
RUN unzip -o /tmp/phpredis-master.zip -d /tmp/phpredis-5.6
WORKDIR /tmp/phpredis-5.6/phpredis-master
RUN phpize-5.6
RUN ./configure --with-php-config=php-config-5.6
RUN make
RUN make install
RUN echo 'extension=redis.so' >> /phpfarm/inst/php-5.6.39/etc/php.ini

RUN mkdir /tmp/phpredis-7.0
RUN unzip -o /tmp/phpredis-master.zip -d /tmp/phpredis-7.0
WORKDIR /tmp/phpredis-7.0/phpredis-master
RUN phpize-7.0
RUN ./configure --with-php-config=php-config-7.0
RUN make
RUN make install
RUN echo 'extension=redis.so' >> /phpfarm/inst/php-7.0.33/etc/php.ini

WORKDIR /app/cache
VOLUME ["/app/cache"]

RUN curl -sS https://getcomposer.org/installer | php-5.6 && mv /app/cache/composer.phar /usr/local/bin/composer